user_input1 = input("what is your favorite animal: ")
user_input2 = input("why is that your favorite animal: ")
user_input3 = input("what is the most common color they are likely to be: ")
user_input4 = input("If you had ever had one as a pet what would you name it: ")
user_input5 = input("where do they live: ")
user_input6 = input("what is needed in it's habitat: ")
user_input7 = input("are they a carnivore omnivor or a herbavor: ")
user_input8 = input("what are the preditors of a " + user_input1 + ": ")
user_input9 = input("are you likely or unlikley to spot it in the wild: ")
user_input0 = input("does it reproduce asexualy or sexualy: ")
print("you like " + user_input1 + "'s. This is your favorite animal is a " + user_input1 + " because " + user_input2 + ". They are usualy the color " + user_input3 + ". If they could be your pet you would name it " + user_input4 + ". They live in " + user_input5 + ". It's habitat needs " + user_input6 + ". They are a " + user_input7 + ". Their natural preditors are " + user_input8 + ". You are " + user_input9 + " to see this in the wild." +  " It reproduces " + user_input0 + ".")
