potato = input("what is your favorite animal:\n>")
f2_is_usefull = input("why is that your favorite animal:\n>")
user_input3 = input("what is the most common color they are likely to be:\n>")
user_input4 = input("If you ever had one as a pet what would you name it:\n>")
user_input5 = input("where do they live:\n>")
user_input6 = input("what is needed in it's habitat:\n>")
user_input7 = input("are they a carnivore omnivor or a herbavor:\n>")
user_input8 = input("what are the preditors of a " + potato + ":\n>")
user_input9 = input("are you likely or unlikley to spot it in the wild where you live: \n>")
user_input0 = input("does it reproduce sexually or asexually \n>")
god_damn = input("how many babies are usually had in each liter \n>")
print("you like " + potato + "'s. This is your favorite animal because a " + potato + " because " + f2_is_usefull + ". They are usualy the color " + user_input3 + ". If they could be your pet you would name it " + user_input4 + ". They live in " + user_input5 + ". It's habitat needs " + user_input6 + ". They are " + user_input7 + "'s. Their natural predators are " + user_input8 + ". You are " + user_input9 + " to see this in the wild. A " + potato + " reproduces " + user_input0 + ", and the avarage number of babies in a litter of " + potato + "'s is usually " + god_damn + ".")